FROM node:22-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS runner
COPY --from=deps /app/node_modules ./node_modules
COPY . .

CMD ["npx", "ts-node", "--project", "tsconfig.migrations.json", "node_modules/typeorm/cli.js", "migration:run", "-d", "typeorm.config.ts"]
