FROM node:22-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

ENV NODE_ENV=development
ENV WATCHPACK_POLLING=true
EXPOSE 3000

CMD ["npx", "next", "dev", "--webpack"]
